version: 2.1


executors:
  python-executor:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/repo


defaults: &defaults
  executor: python-executor
  working_directory: ~/repo

jobs:
  setup_and_install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install --quiet -r requirements.txt
            sudo python setup.py develop

      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7.4/site-packages"
      - run:
          command: |
            echo list files
            ls

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: ~/
          # Must be relative path from root
          paths:
            - repo

  evaluator_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          command: |
            echo list files
            ls
      - run:
          name: Evaluator tests
          command:
            python ~/repo/tests/test_evaluation.py

  data_quality_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Data Quality Tests
          command: |
            python ~/repo/tests/data_format_tests.py
            python ~/repo/tests/usgs_tests.py
            python ~/repo/tests/test_join.py

  model_basic_test:
    <<: *defaults
    steps:
      - run:
          name: Model basic tests
          when: always
          command: |
            python tests/time_model_test.py
            python tests/pytorc_train_tests.py
            python tests/model_config_tests.py
            python tests/data_loader_tests.py
            python tests/test_da_rnn.py

  decoder_test:
    working_directory: ~/repo
    executor: python-executor
    steps:
      - run:
          name: Decoder tests
          when: always
          command:
            python tests/test_decoder.py

  trainer_test:
    working_directory: ~/repo
    executor: python-executor
    steps:
      - run:
          name: Trainer tests
          when: always
          command: |
            python flood_forecast/trainer.py -p tests/lstm_test.json
            python flood_forecast/trainer.py -p tests/multi_test.json
            python flood_forecast/trainer.py  -p tests/full_transformer.json
            python flood_forecast/trainer.py -p tests/decoder_test.json
            python flood_forecast/trainer.py -p tests/custom_encode.json

  plot_test:
    working_directory: ~/repo
    executor: python-executor
    steps:
      - run:
          name: plot tests
          when: always
          command:
            python tests/test_plot.py
#          - run:
#              name: Plot tests
#              when: always
#              command:
#                python tests/test_plot.py
#          - store_artifacts:
#              path: test-reports
#              destination: test-reports

workflows:
  version: 2

  test_and_build:
    jobs:
      - setup_and_install
      - evaluator_test:
          requires:
            - setup_and_install
      - data_quality_test:
          requires:
            - setup_and_install
      - model_basic_test:
          requires:
            - setup_and_install
      - decoder_test:
          requires:
            - setup_and_install
      - trainer_test:
          requires:
            - setup_and_install
      - plot_test:
          requires:
            - setup_and_install
