version: 2.1


executors:
  python-executor:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/repo


defaults: &defaults
  executor: python-executor
  working_directory: ~/repo

jobs:
  setup_and_install:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  evaluator_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install --quiet -r requirements.txt
            sudo python setup.py develop --no-deps

      - save_cache:
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local

      - run:
          name: Evaluator tests
          command:
            python -m unittest -v tests/test_evaluation.py

      - store_test_results:
          path: test-results-evaluator


  data_quality_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install --quiet -r requirements.txt
            sudo python setup.py develop --no-deps

      - save_cache:
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local

      - run:
          name: Data Quality Tests
          command: |
            python -m unittest -v tests/data_format_tests.py
            python -m unittest -v tests/usgs_tests.py
            python -m unittest -v tests/test_join.py

      - store_test_results:
          path: test-results-data-quality


  model_basic_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install --quiet -r requirements.txt
            sudo python setup.py develop --no-deps

      - save_cache:
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local

      - run:
          name: Model basic tests
          when: always
          command: |
            python -m unittest -v tests/time_model_test.py
            python -m unittest -v tests/pytorc_train_tests.py
            python -m unittest -v tests/model_config_tests.py
            python -m unittest -v tests/data_loader_tests.py
            python -m unittest -v tests/test_da_rnn.py

      - store_test_results:
          path: test-results-model-tests

  decoder_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install --quiet -r requirements.txt
            sudo python setup.py develop --no-deps

      - save_cache:
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local

      - run:
          name: Decoder tests
          when: always
          command:
            python -m unittest -v tests/test_decoder.py

      - store_test_results:
          path: test-results-decoder


  trainer_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install --quiet -r requirements.txt
            sudo python setup.py develop --no-deps

      - save_cache:
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local

      - run:
          name: Trainer tests
          when: always
          command: |
            echo -e 'running trainer_lstm_test \n'
            python flood_forecast/trainer.py -p tests/lstm_test.json
            echo -e 'running trainer_multi_test \n'
            python flood_forecast/trainer.py -p tests/multi_test.json
            echo -e 'running trainer_full_transformer_test \n'
            python flood_forecast/trainer.py -p  tests/full_transformer.json
            echo -e 'running trainer_decoder_test \n'
            python flood_forecast/trainer.py -p tests/decoder_test.json
            echo -e 'running trainer_custom_encode \n'
            python flood_forecast/trainer.py -p tests/custom_encode.json

      - store_test_results:
          path: test-results-trainer


  plot_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install --quiet -r requirements.txt
            sudo python setup.py develop --no-deps

      - save_cache:
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local

      - run:
          name: plot tests
          when: always
          command: |
            python -m unittest -v tests/test_plot.py
            python -m unittest -v tests/test_explain_model_output.py

      - store_test_results:
          path: test-results-plot


workflows:
  version: 2

  test_and_build:
    jobs:
      - setup_and_install
      - evaluator_test:
          requires:
            - setup_and_install
      - data_quality_test:
          requires:
            - setup_and_install
      - model_basic_test:
          requires:
            - setup_and_install
      - decoder_test:
          requires:
            - setup_and_install
      - trainer_test:
          requires:
            - setup_and_install
      - plot_test:
          requires:
            - setup_and_install
