version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/repo

jobs:
  flow:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install -r requirements.txt
            sudo python setup.py develop

  evaluator_test:
    executor: python-executor
    steps:
      - run:
          name: Evaluator tests
          command:
            python tests/test_evaluation.py

  data_quality_test:
    executor: python-executor
    steps:
      - run:
          name: Data Quality Tests
          command: |
            python tests/data_format_tests.py
            python tests/usgs_tests.py
            python tests/test_join.py

  model_basic_test:
    executor: python-executor
    steps:
      - run:
          name: Model basic tests
          when: always
          command: |
            python tests/time_model_test.py
            python tests/pytorc_train_tests.py
            python tests/model_config_tests.py
            python tests/data_loader_tests.py
            python tests/test_da_rnn.py

  decoder_test:
    executor: python-executor
    steps:
      - run:
          name: Decoder tests
          when: always
          command:
            python tests/test_decoder.py

  trainer_test:
    executor: python-executor
    steps:
      - run:
          name: Trainer tests
          when: always
          command: |
            python flood_forecast/trainer.py -p tests/lstm_test.json
            python flood_forecast/trainer.py -p tests/multi_test.json
            python flood_forecast/trainer.py  -p tests/full_transformer.json
            python flood_forecast/trainer.py -p tests/decoder_test.json
            python flood_forecast/trainer.py -p tests/custom_encode.json

  plot_test:
    executor: python-executor
    steps:
      - run:
          name: plot tests
          when: always
          command:
            python tests/test_plot.py
#          - run:
#              name: Plot tests
#              when: always
#              command:
#                python tests/test_plot.py
#          - store_artifacts:
#              path: test-reports
#              destination: test-reports

workflows:
  version: 2

  test_and_build:
    jobs:
      - flow
      - evaluator_test:
          requires:
            - flow
      - data_quality_test:
          requires:
            - flow
      - model_basic_test:
          requires:
            - flow
      - decoder_test:
          requires:
            - flow
      - trainer_test:
          requires:
            - flow
      - plot_test:
          requires:
            - flow
