version: 2.1


executors:
  python-executor:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/repo


defaults: &defaults
  executor: python-executor
  working_directory: ~/repo


_run:
  setenv: &setenv
    command: |-
      echo -e "export CIRCLE_WORKING_DIR=${HOME}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" >> $BASH_ENV
      echo -e "export PATH=${PATH}:${HOME}/.yarn/bin:\${CIRCLE_WORKING_DIR}/node_modules/.bin" >> $BASH_ENV
      echo -e "export DISPLAY=:1.0" >> $BASH_ENV
      case $CIRCLE_NODE_INDEX in
        2|3)  echo -e "export ZOTERO=jurism" >> $BASH_ENV
              ;;
        *)    echo -e "export ZOTERO=zotero" >> $BASH_ENV
              ;;
      esac
      git log --format=%B -n 1 $CIRCLE_SHA1 | grep '#trace' &> /dev/null
      if [ $? == 0 ]; then
        echo -e "export TRACE=true" >> $BASH_ENV
      fi
  ruby: &ruby
    command: gem install bundler && gem update bundler && bundle config && (bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3)
    no_output_timeout: 180s
  node: &node
    command: yarn install

setup_step: &setup_step
  - attach_workspace:
      at: ~/repo
  - restore_cache:  # ensure this step occurs *before* installing dependencies
      key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

  - run:
      name: install dependencies
      command: |
        sudo pip install pipenv
        sudo pip install --quiet -r requirements.txt
        sudo python setup.py develop --no-deps

  - save_cache:
      key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
      paths:
        - ~/.local
  - run:
      command: |
        echo list files
        ls -R

jobs:
  setup_and_install:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  evaluator_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          command: |
            echo list files
            ls -R
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install --quiet -r requirements.txt
            sudo python setup.py install

      - save_cache:
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local
      - run:
          command: |
            echo list files
            ls -R

      - run:
          name: Evaluator tests
          command:
            python tests/test_evaluation.py

  data_quality_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install --quiet -r requirements.txt
            sudo python setup.py develop --no-deps

      - save_cache:
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local
      - run:
          command: |
            echo list files
            ls -R
      - run:
          command: |
            echo list files
            ls -R
      - run:
          name: Data Quality Tests
          command: |
            python tests/data_format_tests.py
            python tests/usgs_tests.py
            python tests/test_join.py

  model_basic_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install --quiet -r requirements.txt
            sudo python setup.py develop --no-deps

      - save_cache:
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local
      - run:
          command: |
            echo list files
            ls -R

      - run:
          name: Model basic tests
          when: always
          command: |
            python tests/time_model_test.py
            python tests/pytorc_train_tests.py
            python tests/model_config_tests.py
            python tests/data_loader_tests.py
            python tests/test_da_rnn.py

  decoder_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install --quiet -r requirements.txt
            sudo python setup.py develop --no-deps

      - save_cache:
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local
      - run:
          command: |
            echo list files
            ls -R

      - run:
          name: Decoder tests
          when: always
          command:
            python tests/test_decoder.py

  trainer_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install --quiet -r requirements.txt
            sudo python setup.py develop --no-deps

      - save_cache:
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local
      - run:
          command: |
            echo list files
            ls -R

      - run:
          name: Trainer tests
          when: always
          command: |
            python flood_forecast/trainer.py -p tests/lstm_test.json
            python flood_forecast/trainer.py -p tests/multi_test.json
            python flood_forecast/trainer.py -p  tests/full_transformer.json
            python flood_forecast/trainer.py -p tests/decoder_test.json
            python flood_forecast/trainer.py -p tests/custom_encode.json

  plot_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install --quiet -r requirements.txt
            sudo python setup.py develop --no-deps

      - save_cache:
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local
      - run:
          command: |
            echo list files
            ls -R

      - run:
          name: plot tests
          when: always
          command:
            python tests/test_plot.py

#          - store_artifacts:
#              path: test-reports
#              destination: test-reports

workflows:
  version: 2

  test_and_build:
    jobs:
      - setup_and_install
      - evaluator_test:
          requires:
            - setup_and_install
      - data_quality_test:
          requires:
            - setup_and_install
      - model_basic_test:
          requires:
            - setup_and_install
      - decoder_test:
          requires:
            - setup_and_install
      - trainer_test:
          requires:
            - setup_and_install
      - plot_test:
          requires:
            - setup_and_install
